/**
 * Error codes used throughout the application
 */

// HTTP inspired error codes
export const BAD_REQUEST = 'BAD_REQUEST';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
export const NOT_FOUND = 'NOT_FOUND';
export const CONFLICT = 'CONFLICT';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';

// Domain-specific error codes
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';
export const ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND';
export const STUDENT_NOT_ENROLLED = 'STUDENT_NOT_ENROLLED';
export const SUBMISSION_ALREADY_EXISTS = 'SUBMISSION_ALREADY_EXISTS';
export const SUBMISSION_DEADLINE_PASSED = 'SUBMISSION_DEADLINE_PASSED';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
export const INVALID_FILE_TYPE = 'INVALID_FILE_TYPE';
export const DATABASE_ERROR = 'DATABASE_ERROR';

// Auth specific error codes
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const TOKEN_INVALID = 'TOKEN_INVALID';
export const TOKEN_REQUIRED = 'TOKEN_REQUIRED';
export const ACCOUNT_LOCKED = 'ACCOUNT_LOCKED';
export const TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS';

// External service error codes
export const EMAIL_SERVICE_ERROR = 'EMAIL_SERVICE_ERROR';
export const PAYMENT_SERVICE_ERROR = 'PAYMENT_SERVICE_ERROR';
export const STORAGE_SERVICE_ERROR = 'STORAGE_SERVICE_ERROR';
export const AI_SERVICE_ERROR = 'AI_SERVICE_ERROR';

/**
 * Error codes mapped to their HTTP status codes
 */
export const errorCodeToStatusCode: Record<string, number> = {
  [BAD_REQUEST]: 400,
  [UNAUTHORIZED]: 401,
  [FORBIDDEN]: 403,
  [NOT_FOUND]: 404,
  [CONFLICT]: 409,
  [INTERNAL_SERVER_ERROR]: 500,
  [SERVICE_UNAVAILABLE]: 503,
  
  [INVALID_CREDENTIALS]: 401,
  [EMAIL_ALREADY_EXISTS]: 409,
  [USER_NOT_FOUND]: 404,
  [COURSE_NOT_FOUND]: 404,
  [ASSIGNMENT_NOT_FOUND]: 404,
  [STUDENT_NOT_ENROLLED]: 403,
  [SUBMISSION_ALREADY_EXISTS]: 409,
  [SUBMISSION_DEADLINE_PASSED]: 400,
  [FILE_UPLOAD_ERROR]: 500,
  [INVALID_FILE_TYPE]: 400,
  [DATABASE_ERROR]: 500,
  
  [TOKEN_EXPIRED]: 401,
  [TOKEN_INVALID]: 401,
  [TOKEN_REQUIRED]: 401,
  [ACCOUNT_LOCKED]: 403,
  [TOO_MANY_ATTEMPTS]: 429,
  
  [EMAIL_SERVICE_ERROR]: 503,
  [PAYMENT_SERVICE_ERROR]: 503,
  [STORAGE_SERVICE_ERROR]: 503,
  [AI_SERVICE_ERROR]: 503,
}; 